### ISSUE TITLE
ExNavigation 已被官方替换为了 React Navigation

### ISSUE THREAD

**Issue by zhuziyi1989** [ZevenFang/react-native-starterkit#1]
Expo SDK v18.0.0 发布：近日发布的 Expo SDK 18.0.0 版本基于 React Native 0.45，引入了一系列的新特性与性能提升。在该版本中 exp.json 被合并到了 app.json 中，从而简化了 React Native 生态系统与 Expo 使用者之间的差异；并且新的项目不再使用 Expo.registerRootComponent， **ExNavigation 也被替换为了 React Navigation。** 除此之外，Expo 响应的开发工具 XDE、exp、Snack 等也都得到了优化。
( [https://parg.co/byA](https://parg.co/byA) )

**Comment by ZevenFang** [comment]
谢谢提醒，本项目会尽快做版本兼容

**Comment by ZevenFang** [comment]
已经升级 Expo SDK，同时使用 React Navigation 作为导航
